camel:
  component:
    servlet:
      mapping:
        contextPath: /*
server:
  port: 9090


spring:
  datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/eclipseservices
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      max-connections: 10
   

todos:
  queue: jms:todoqueue


      